In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('corrected_calender.csv',encoding='ISO-8859-1')
df

           date
0    01-01-1997
1    02-01-1997
2    03-01-1997
3    04-01-1997
4    05-01-1997
..          ...
725  27-12-1998
726  28-12-1998
727  29-12-1998
728  30-12-1998
729  31-12-1998

[730 rows x 1 columns]

In [5]:
df.dtypes

date    datetime64[ns]
dtype: object

In [4]:
df['date'] = df['date'].astype('datetime64[ns]')

In [6]:
df.to_csv('calender_date_convert.csv',index=False)
df

          date
0   1997-01-01
1   1997-02-01
2   1997-03-01
3   1997-04-01
4   1997-05-01
..         ...
725 1998-12-27
726 1998-12-28
727 1998-12-29
728 1998-12-30
729 1998-12-31

[730 rows x 1 columns]